AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample SAM Template for Lambda custom runtimes

Globals:
  Function:
    Timeout: 10

Resources:
  NaiveJavaRuntimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: NaiveJavaRuntime
      Handler: do.not.apply
      Runtime: provided
      MemorySize: 128
    Metadata:
      BuildMethod: makefile

  FunqyAmazonLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: FunqyAmazonLambda
      Handler: do.not.apply
      Runtime: provided
      MemorySize: 128
      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true
    Metadata:
      BuildMethod: makefile